name: TF Lint
author: Esten Rye
description: Check Terraform code lint
branding:
  icon: check-circle
  color: blue
inputs:
  working_directory:
    description: 'The directory where Terraform files are located'
    required: false
    default: '.'
  tflint_version:
    description: 'The version of TF-Lint to use'
    required: true
    default: latest
  github_token:
    description: 'The GitHub token to use'
    required: true
runs:
    using: 'composite'
    steps:
      # Checkout Repository
      - name : Check out Git Repository
        uses: actions/checkout@v4  

      # TFLint - Terraform Check
      - uses: actions/cache@v4
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v4
        name: Setup TFLint
        with:
          github_token: ${{ inputs.github_token }}
          tflint_version: ${{ inputs.tflint_version }}
        
      # Print TFLint version
      - name: Show version
        shell: bash
        run: tflint --version

      # Install plugins
      - name: Init TFLint
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        run: tflint --init

      # Run tflint command in each directory recursively # use --force if you want to continue with workflow although errors are there
      - name: Run TFLint
        shell: bash
        working-directory: ${{ inputs.working_directory }}
        run: tflint -f compact --recursive
